@host_v1=http://localhost:3055/v1/api

###! Sign Up
POST {{host_v1}}/shop/sign-up
Content-Type: application/json
x-api-key: asdasacads

{
  "name": "Shop minat",
  "email": "minatdev@gmail.com",
  "password": "123456"
}